<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('properties')->insert([
            [
                'title' => 'Căn hộ Quận 1',
                'description' => 'Căn hộ đẹp ở trung tâm Quận 1',
                'property_type' => 'apartment',
                'status' => 'available',
                'price' => 1500000000,
                'area' => 75.5,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'floors' => 10,
                'address' => '123 Đường Lê Lợi',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 1',
                'postal_code' => '700000',
                'latitude' => 10.776530,
                'longitude' => 106.700981,
                'year_built' => 2015,
                'features' => json_encode(['balcony', 'parking']),
                'images' => json_encode([['id' => 1, 'image_path' => '/storage/properties/1.jpg', 'is_primary' => true]]),
                'contact_name' => 'Nguyễn Văn A',
                'contact_phone' => '0909123456',
                'contact_email' => 'vana@example.com',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nhà phố Quận 3',
                'description' => 'Nhà phố 3 tầng, vị trí đẹp',
                'property_type' => 'house',
                'status' => 'available',
                'price' => 3500000000,
                'area' => 120.0,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 3,
                'address' => '456 Đường Võ Văn Tần',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 3',
                'postal_code' => '700000',
                'latitude' => 10.779530,
                'longitude' => 106.688981,
                'year_built' => 2010,
                'features' => json_encode(['garage', 'garden']),
                'images' => json_encode([['id' => 2, 'image_path' => '/storage/properties/2.jpg', 'is_primary' => true]]),
                'contact_name' => 'Trần Thị B',
                'contact_phone' => '0912345678',
                'contact_email' => 'thib@example.com',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Căn hộ Quận 7',
                'description' => 'Căn hộ cao cấp, view sông',
                'property_type' => 'apartment',
                'status' => 'sold',
                'price' => 2000000000,
                'area' => 90.0,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 15,
                'address' => '789 Đường Nguyễn Văn Linh',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 7',
                'postal_code' => '700000',
                'latitude' => 10.732530,
                'longitude' => 106.700081,
                'year_built' => 2018,
                'features' => json_encode(['pool', 'gym']),
                'images' => json_encode([['id' => 3, 'image_path' => '/storage/properties/3.jpg', 'is_primary' => true]]),
                'contact_name' => 'Lê Văn C',
                'contact_phone' => '0987654321',
                'contact_email' => 'vanc@example.com',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Biệt thự Quận 2',
                'description' => 'Biệt thự sang trọng, nhiều cây xanh',
                'property_type' => 'villa',
                'status' => 'available',
                'price' => 8000000000,
                'area' => 350.0,
                'bedrooms' => 6,
                'bathrooms' => 5,
                'floors' => 2,
                'address' => '321 Đường Thảo Điền',
                'city' => 'Hồ Chí Minh',
                'district' => 'Quận 2',
                'postal_code' => '700000',
                'latitude' => 10.781530,
                'longitude' => 106.745981,
                'year_built' => 2012,
                'features' => json_encode(['garden', 'garage', 'pool']),
                'images' => json_encode([['id' => 4, 'image_path' => '/storage/properties/4.jpg', 'is_primary' => true]]),
                'contact_name' => 'Phạm Thị D',
                'contact_phone' => '0908765432',
                'contact_email' => 'thid@example.com',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Căn hộ Bình Thạnh',
                'description' => 'Căn hộ tiện nghi, gần trung tâm',
                'property_type' => 'apartment',
                'status' => 'available',
                'price' => 1300000000,
                'area' => 68.0,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 8,
                'address' => '654 Đường Phan Văn Trị',
                'city' => 'Hồ Chí Minh',
                'district' => 'Bình Thạnh',
                'postal_code' => '700000',
                'latitude' => 10.800530,
                'longitude' => 106.700381,
                'year_built' => 2016,
                'features' => json_encode(['balcony']),
                'images' => json_encode([['id' => 5, 'image_path' => '/storage/properties/5.jpg', 'is_primary' => true]]),
                'contact_name' => 'Ngô Văn E',
                'contact_phone' => '0934567890',
                'contact_email' => 'vane@example.com',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
